# File generated by CMake process
set(sources BinaryChunk.cpp;Chunk.cpp;ChunkGenerator.cpp;ColorMapper.cpp;Core.cpp;CubicChunk.cpp;DebugScene.cpp;DualChunk.cpp;DynamicGLChunk.cpp;Entry.cpp;FPSCamera.cpp;GLChunk.cpp;ImplicitSampler.cpp;MeshProcessor.cpp;NoiseSampler.cpp;PCH.cpp;WorldOctree.cpp;WorldOctreeNode.cpp;WorldStitcher.cpp;WorldWatcher.cpp)
