# File generated by CMake process
set(sources ChunkGenerator.cpp;ColorMapper.cpp;Core.cpp;DMCChunk.cpp;DebugScene.cpp;DynamicGLChunk.cpp;Entry.cpp;FPSCamera.cpp;Frustum.cpp;GLChunk.cpp;ImplicitSampler.cpp;MeshProcessor.cpp;NoiseSampler.cpp;PCH.cpp;Texture.cpp;WorldOctree.cpp;WorldOctreeNode.cpp;WorldStitcher.cpp;WorldWatcher.cpp)
